Kfalvestad/event page
echo-webkom/new-echo-web-monorepo pull request #354
Opened 2023-06-12 14:59 UTC by kfalvestad

## Why did you create this PR?

Tanken er å ha en oversiktelig og brukervennelig oversikt og søkesystem for alle bedpresser og arrangementer. Lager en draft nå for å se hva dere synes om designet. Hvis det ikke er overkill, så tenker jeg at det også er kult å kunne filtrere etter undergrupper, i form av egen checkbox meny under "tidspunkter", men prisma er fucked for meg atm så det får bli senere. 

## How did you solve the problem?

Laget et utkast til arrangementsiden ved god hjelp av Torger. Tar gjerne i mot tilbakemelding på både design og funskjon!

2023-06-13 05:04 UTC, omfj requested changes

2023-06-13 05:04 UTC, omfj commented on apps/web/src/app/(default)/arrangementer/page.tsx
> +  }
Hva er meningen her? Vi vet du allerede at en happening er en bedpres eller event.

2023-06-13 10:49 UTC, kfalvestad commented on apps/web/src/app/(default)/arrangementer/page.tsx
> +  }
Tanken er vel å gi de en "type" property, sånn at det blir lettere å skille mellom de i filtreringen. Kan kanskje gjøres mer effektivt?

2023-06-13 14:11 UTC, omfj commented on apps/web/src/app/(default)/arrangementer/page.tsx
> +  }
Jo, men `instanceof` har med klasser å gjøre. Hvis du vil sjekke senere om noe er en event eller ikke kan du lage en type guard.

2023-07-29 16:42 UTC, omfj commented
Veldig pent, digger designet.

Det som hadde vært nice var om var en tekst når ingen resultater vises. Typ finner "ingen arrg som passer dine filter" eller noe.

Tror du også at du får til å gjøre dette på server side? At vi da bruker search params for å hente ut filtere? https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional

2023-10-11 12:03 UTC, closed without merging