Izaak/valider at sporsmal fins
echo-webkom/new-echo-web-monorepo pull request #679
Opened 2023-09-27 11:02 UTC by izaaksarnecki1

## Why did you create this PR?

Vi manglet validering på påmeldingen til arrangement.

## How did you solve the problem?

Vi la inn en sjekk at hvert spørsmål arrangementet ble svart på en gang.

2023-09-28 17:48 UTC, omfj commented
Etter litt testing ser det ut som om at jeg fortsatt får lov til å melde meg på selv om jeg ikke har svart på noe av spørsmålene.

Jeg hadde prøvd denne koden her.

```ts
const allQuestionsAnswered = happening.questions.every((question) => {
  const answer = input.questions.find((answer) => answer.question === question.title);
  return !question.required || answer?.answer;
});

if (!allQuestionsAnswered) {
  return NextResponse.json(
    {
      title: "En feil har skjedd",
      description: "Du har ikke svart på alle spørsmålene.",
    },
    {
      status: 400,
    },
  );
}
```

2023-10-03 22:35 UTC, NixEngh commented
Slik det er nå mangler vi enda noen småting. De siste endringene vi gjorde (fjerne det som er kommentert og unødvendige typer), er for eksempel ikke commitet/pushet enda. I tillegg lagrer vi i øyeblikket selve spørsmålet og ikke svaret i Answer tabellen ( nok min feil 😅 )

2023-10-04 20:43 UTC, omfj requested changes

2023-10-04 20:43 UTC, omfj commented on apps/web/src/app/api/happening/[slug]/register/route.ts
> +          for (var happeningQuestion of happening.questions) {
Her kan men heller bruker `const` istedenfor `var`. Generelt alltid bruker `const`. Om `const` ikke funker, så bruker man oftest `let`.

https://dev.to/paritho/3-reasons-to-use-var-in-javascript-1hoe

2023-10-07 17:43 UTC, omfj approved these changes

2023-10-07 17:47 UTC, merged