Omfj/add sanity
echo-webkom/new-echo-web-monorepo pull request #73
Opened 2023-03-27 10:16 UTC by Epirius

**[ChatGPT]**

Sure, I can help you write a short pull request for your sanity schema. Here's an example:

Subject: Pull Request for Sanity Schema Implementation

Hi [Name of your manager or colleague],

I hope this message finds you well. I wanted to let you know that I have completed the initial sanity schema for our new website. This schema will help ensure that the data entered into our content management system (CMS) is structured and consistent, which will ultimately improve the quality of our website.

The schema includes the following features:

Defined document types with clear fields and data types
Validation rules to prevent incorrect data entry
Custom inputs to guide content creators on how to enter data
Portable text for flexible content creation
I have tested the schema extensively and made sure that it meets the requirements of our website. I have also documented the schema and created a simple guide for content creators to follow.

Please review the pull request and let me know if you have any feedback or suggestions. I believe that this schema will be a valuable addition to our website development process.

Thank you for your time and consideration.

Best regards,
[Your name]

2023-03-27 10:26 UTC, omfj commented
Crazy PR melding

2023-03-27 11:10 UTC, omfj requested changes

2023-03-27 11:10 UTC, omfj commented on apps/cms/package.json
> +  }
```suggestion
```

Denne kan fjernes. Siden vi har allerede `prettier` i root dir.

2023-03-27 11:10 UTC, omfj commented on apps/cms/.eslintrc
> +  "extends": "@sanity/eslint-config-studio"
```suggestion
  "extends": ["custom", "@sanity/eslint-config-studio"]
```
Her tror jeg du kan legge til våres egen `eslint` config, og extende begge.

2023-03-29 10:49 UTC, omfj commented
@bocianowski1 Hvis du vil ha noe gjøre kan du hjelpe til med Sanity. Du har vel ikke jobbet så mye med det før heller, så her er det mye å lære.

2023-03-30 14:26 UTC, omfj commented
Da tror jeg alt av felt og schema skal være på plass.

2023-04-03 10:52 UTC, omfj commented
review plz 🥺

2023-04-04 08:34 UTC, bocianowski1 submitted a review, later dismissed
Dette ser bra ut!

2023-04-05 09:15 UTC, merged