Swarnika/user management
echo-webkom/new-echo-web-monorepo pull request #731
Opened 2023-10-07 17:45 UTC by tjekol

## Why did you create this PR?

Slik at admin brukere kan endre hvilke grupper brukere er del av, og gjøre brukere til admin.

## How did you solve the problem?

At knappen endre rolle på brukere dashboard faktisk gjør noe.

2023-10-07 17:56 UTC, tjekol commented
Koffer feile deploy 😢? @omfj

2023-10-07 18:41 UTC, omfj commented
Tror det skal funke nå. Om dette skjer igjen så er det nok bare å slett resource groupen i Azure og re-runne joben.

2023-10-09 17:19 UTC, omfj requested changes
Kanskje endret litt farge på den switchen. Litt lite kontrast, og kanskje endre farge til den blå fargen som vi har på checkboxene.

Er det også mulig å gjøre den "Endre rolle"-knappen full bredde?

2023-10-18 16:11 UTC, omfj commented
Oj. Her var et mye som har skjedd.

2023-10-19 11:20 UTC, omfj commented
Jeg gjorde switchen sånn @tjekol, om det går fint.

![CleanShot 2023-10-19 at 13 19 39@2x](https://github.com/echo-webkom/new-echo-web-monorepo/assets/32321558/3beea76f-b8bb-4ce0-b068-23fb07433062)

2023-10-19 11:20 UTC, omfj approved these changes

2023-10-19 11:41 UTC, merged