add: header logo animation and rounded avatar images
echo-webkom/new-echo-web-monorepo pull request #82
Opened 2023-03-30 14:41 UTC by bocianowski1

Scaler logoen on scroll og gjorde avatar-bildene runde. Ser litt bedre ut når bildene på hovedstyre-section animeres inn.

2023-03-30 14:47 UTC, omfj commented
Heftig. Kan vi gjøre det sånn at avatarene bare animerer første gangen og ikke hver gang du scroller forbi?

2023-03-30 18:30 UTC, bocianowski1 commented
Ja syns det er irriterende sjæl

2023-03-30 18:43 UTC, omfj requested changes

2023-03-30 18:43 UTC, omfj commented on apps/web/src/components/avatar.tsx
> -    className={cn("aspect-square h-full w-full", className)}
Jeg tror vi fortsatt har lyst til å ha `aspect-square` her

2023-03-30 20:53 UTC, omfj requested changes

2023-03-31 10:24 UTC, omfj approved these changes

2023-03-31 10:26 UTC, merged